package com.nyu.entity;
// Generated 2015-9-3 13:08:50 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "test")
public class User implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String email;
	private Integer sex;
	private Date createTime;
	private Set<Video> videos = new HashSet<Video>(0);
	private Set<Danmu> danmus = new HashSet<Danmu>(0);
	private Set<Comments> commentses = new HashSet<Comments>(0);
	private Set<Comment> comments = new HashSet<Comment>(0);

	public User() {
	}

	public User(String username, String password, String email, Integer sex, Date createTime, Set<Video> videos,
			Set<Danmu> danmus, Set<Comments> commentses, Set<Comment> comments) {
		this.username = username;
		this.password = password;
		this.email = email;
		this.sex = sex;
		this.createTime = createTime;
		this.videos = videos;
		this.danmus = danmus;
		this.commentses = commentses;
		this.comments = comments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", length = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "sex")
	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Video> getVideos() {
		return this.videos;
	}

	public void setVideos(Set<Video> videos) {
		this.videos = videos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Danmu> getDanmus() {
		return this.danmus;
	}

	public void setDanmus(Set<Danmu> danmus) {
		this.danmus = danmus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Comments> getCommentses() {
		return this.commentses;
	}

	public void setCommentses(Set<Comments> commentses) {
		this.commentses = commentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

}
