package com.nyu.entity;
// Generated 2015-9-3 15:06:11 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Video generated by hbm2java
 */
@Entity
@Table(name = "video", catalog = "test")
public class Video implements java.io.Serializable {

	private Integer id;
	private User user;
	private String videoname;
	private String videoinr;
	private Integer playnum;
	private Integer collectnum;
	private String img;
	private Date createtime;
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<Danmu> danmus = new HashSet<Danmu>(0);

	public Video() {
	}

	public Video(User user, String videoname, String videoinr, Integer playnum, Integer collectnum, String img,
			Date createtime, Set<Comment> comments, Set<Danmu> danmus) {
		this.user = user;
		this.videoname = videoname;
		this.videoinr = videoinr;
		this.playnum = playnum;
		this.collectnum = collectnum;
		this.img = img;
		this.createtime = createtime;
		this.comments = comments;
		this.danmus = danmus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "uid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "videoname", length = 100)
	public String getVideoname() {
		return this.videoname;
	}

	public void setVideoname(String videoname) {
		this.videoname = videoname;
	}

	@Column(name = "videoinr", length = 100)
	public String getVideoinr() {
		return this.videoinr;
	}

	public void setVideoinr(String videoinr) {
		this.videoinr = videoinr;
	}

	@Column(name = "playnum")
	public Integer getPlaynum() {
		return this.playnum;
	}

	public void setPlaynum(Integer playnum) {
		this.playnum = playnum;
	}

	@Column(name = "collectnum")
	public Integer getCollectnum() {
		return this.collectnum;
	}

	public void setCollectnum(Integer collectnum) {
		this.collectnum = collectnum;
	}

	@Column(name = "img", length = 100)
	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "video")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "video")
	public Set<Danmu> getDanmus() {
		return this.danmus;
	}

	public void setDanmus(Set<Danmu> danmus) {
		this.danmus = danmus;
	}

}
